module.exports = (function() {
var __MODS__ = {};
var __DEFINE__ = function(modId, func, req) { var m = { exports: {}, _tempexports: {} }; __MODS__[modId] = { status: 0, func: func, req: req, m: m }; };
var __REQUIRE__ = function(modId, source) { if(!__MODS__[modId]) return require(source); if(!__MODS__[modId].status) { var m = __MODS__[modId].m; m._exports = m._tempexports; var desp = Object.getOwnPropertyDescriptor(m, "exports"); if (desp && desp.configurable) Object.defineProperty(m, "exports", { set: function (val) { if(typeof val === "object" && val !== m._exports) { m._exports.__proto__ = val.__proto__; Object.keys(val).forEach(function (k) { m._exports[k] = val[k]; }); } m._tempexports = val }, get: function () { return m._tempexports; } }); __MODS__[modId].status = 1; __MODS__[modId].func(__MODS__[modId].req, m, m.exports); } return __MODS__[modId].m.exports; };
var __REQUIRE_WILDCARD__ = function(obj) { if(obj && obj.__esModule) { return obj; } else { var newObj = {}; if(obj != null) { for(var k in obj) { if (Object.prototype.hasOwnProperty.call(obj, k)) newObj[k] = obj[k]; } } newObj.default = obj; return newObj; } };
var __REQUIRE_DEFAULT__ = function(obj) { return obj && obj.__esModule ? obj.default : obj; };
__DEFINE__(1716001926371, function(require, module, exports) {
var t={d:(o,e)=>{for(var a in e)t.o(e,a)&&!t.o(o,a)&&Object.defineProperty(o,a,{enumerable:!0,get:e[a]})},o:(t,o)=>Object.prototype.hasOwnProperty.call(t,o)},o={};t.d(o,{Ay:()=>u,gk:()=>s,Jv:()=>i,IX:()=>c});var e={},a=null,r={},n={};function s(t){var o={};for(var r in t)if(Object.hasOwnProperty.call(t,r)){var n=t[r].split(".")[0],s=e[n];s||(s=new Map).set(this,new Set),s.has(this)||s.set(this,new Set),s.get(this).add(r),e[n]=s,null!=a[n]&&(o[r]=a[n])}this.setData(o)}function i(){var t=arguments[0];if(!t)return console.error("请输入store的mutations名称");r[t]?(arguments[0]=a,r[t].apply(this,Array.prototype.slice.call(arguments))):console.error("未找到".concat(t,",请输入store正确的mutations"))}function c(){var t=arguments[0];if(!t)return console.error("请输入store的actions名称");n[t]?(arguments[0]={storeCommit:i},n[t].apply(this,Array.prototype.slice.call(arguments))):console.error("未找到".concat(t,",请输入store正确的actions"))}function l(){if(a)for(var t in a)Object.hasOwnProperty.call(a,t)&&e[t]&&e[t].has(this)&&e[t].delete(this)}var h,p;h=Page,Page=function(t){t.$setStoreToPage=s,t.$storeCommit=i,t.$storeDispatch=c,t.onUnload||(t.onUnload=function(){});var o=t.onUnload;t.onUnload=function(){return l.call(this),o.apply(this,Array.prototype.slice.call(arguments))},h(t)},p=Component,Component=function(t){t.methods||(t.methods={}),t.methods.$setStoreToPage=s,t.methods.$storeCommit=i,t.methods.$storeDispatch=c,t.detached||(t.detached=function(){});var o=t.detached;t.detached=function(){return l.call(this),o.apply(this,Array.prototype.slice.call(arguments))},p(t)},console.log("%c当前wxminiSharedData版本：1.0.0","color: red;");const u=function(t){return t.data||(t.data={}),t.actions||(t.actions={}),a=new Proxy(t.data,{get:function(t,o){return t[o]},set:function(t,o,a){if(null!=t[o]){t[o]=a;var r=e[o];return r&&r.forEach((function(t,o){var e={};t.forEach((function(t){e[t]=a})),o.setData(e)})),!0}return console.log("Setting property '".concat(o,"' is not allowed.")),!1}}),r=t.mutations,n=t.actions,{data:a,mutations:r,actions:n}};var d=o.Ay,f=o.gk,m=o.Jv,y=o.IX;if (!exports.__esModule) Object.defineProperty(exports, "__esModule", { value: true });Object.defineProperty(exports, 'default', { enumerable: true, configurable: true, get: function() { return d; } });Object.defineProperty(exports, 'setStoreToPage', { enumerable: true, configurable: true, get: function() { return f; } });Object.defineProperty(exports, 'storeCommit', { enumerable: true, configurable: true, get: function() { return m; } });Object.defineProperty(exports, 'storeDispatch', { enumerable: true, configurable: true, get: function() { return y; } });
}, function(modId) {var map = {}; return __REQUIRE__(map[modId], modId); })
return __REQUIRE__(1716001926371);
})()
//miniprogram-npm-outsideDeps=[]
//# sourceMappingURL=index.js.map